# Don't remove the version setting.
version: 1.3

# Specify the name of the map. It will be displayed in the Scoreboard.
name: "&fDefault"
# Specify an asterisk symbol or another symbol that will indicate a victory.
# Leave this blank to display numbers.
star: "★"
entity:
  # Specify the entity.
  type: CHICKEN
  # Specify the speed of mob.
  speed: 0.3
player:
  # Specify the maximum number of hit points. 2 hit points = 1 heart.
  health: 6
  # Specify the bomb damage.
  damageBomb: 2
  # Specify the radius from the finish line at which victory can appear. (For mobs that are very tall)
  radiusFinish: 0.5
# Coordinates of the schematic insertion.
coords:
  x: 0
  y: 100
  z: 0
# Location during teleportation.
location:
  # What yaw will be assigned during teleportation?
  yaw: 180
  # Which north will be assigned during teleportation?
  north: 0
locs:
  # Specify through: ";" - X, Y, Z from the location of the schematic.
  spawn: "0.5;0;0.5"
  # The block that will be used to start the game. (Works worldwide)
  # Remove the extra blocks for teleportation at this Z coordinate. (To avoid accidentally entering parkour)
  portal: "0;0;-7"
  # The starting point where the chicken will run.
  start: "0;0;-12"
  # End.
  end: "0;0;-102"
stars:
  # 1 - 100%.
  # 0.8 - 80%.
  # 0.1 - 10%.
  # Percent
  5: 0.9
  4: 0.75
  3: 0.5
  2: 0.3
  1: 0.15

# Stands.
stands:
  # Specify the radius for the stands to appear.
  radiusStands: 5
  # Set a timer before the bomb explodes.
  timer: 20 # В тиках. 20 тиков - 1 секунда.
  # Specify where the stands will appear.
  # Order: type;X;Y;Z (from the location of the schematic)
  locs:
  - "gold_block;-2;1;-24"
  - "bomb_blue;0;1;-36"
  - "diamond_block;2;2;-47"
  - "gold_block;-2;2;-57"
  - "diamond_block;2;1;-69"
  - "bomb_blue;0;1;-79"
  - "bomb_gold;0;0;-94"
# Set up the message.
# This will only work if you have selected the plugin configuration mode.
messages:
  # Actions. These actions perform the same role as in the config.
  # But there is no support for other languages here.
  actions:
    ingame:
      - "[log] [SCHEMATIC] The %player% cannot perform a certain action while in the game."
    end:
      - "[log] [SCHEMATIC] The %player% has finished the game."
    kicked:
      - "[log] [SCHEMATIC] The %player% was kicked out of the game."
    restarted:
      - "[log] [SCHEMATIC] The game has been restarted."
    damageHeart:
      - "[log] [SCHEMATIC] The %player% lost a heart."
    win:
      - "[log] [SCHEMATIC] The %player% won and got a score &e%star_win%&7%star_loss%"
  # The star rating system.
  stars:
    # 1 - 100%.
    # 0.8 - 80%.
    # 0.1 - 10%.
    # Specify additional actions below. You can view them in the configuration.
    5:
      - "&e★★★★★"
    4:
      - "&e★★★★&7★"
    3:
      - "&e★★★&7★★"
    2:
      - "&e★★&7★★★"
    1:
      - "&e★&7★★★★"
    0:
      - "&7★★★★★"