# Укажите название карты. Оно будет отображаться в Scoreboard.
name: "&fDefault"
# Укажите символ звёздочки или другой который будет показывать победу.
# Оставьте это пустым, чтобы выводились цифры.
star: "★"
entity:
  # Укажите сущность.
  type: CHICKEN
  # Укажите скорость курицы.
  speed: 0.3
player:
  # Укажите максимальное количество хп. 2 хп - 1 сердечко.
  health: 6
  # Укажите урон от бомбы.
  damageBomb: 2
  # Укажите радиус от финиша при котором может появиться победа? (Для мобов которые очень высокие)
  radiusFinish: 0.5
# Координаты вставки схематики
coords:
  x: 0
  y: 100
  z: 0
# Локация при телепортации.
location:
  # Какой yaw будет назначен при телепортации?
  yaw: 180
  # Какой north будет назначен при телепортации?
  north: 0
  # Счёт идёт от высоты игрока.
  # Укажите высоту, которая будет считаться проигрышной.
  loss: 98
locs:
  # Укажите через: ";" - X, Y, Z от места установки схематики.
  spawn: "0.5;0;0.5"
  # Блок, который будет использоваться для начала игры. (Работает по всему миру)
  # Уберите лишние блоки для телепортации на этой Z координате. (Чтобы избежать случайного попадания в паркур)
  portal: "0;0;-7"
  # Место начала, где курица побежит.
  start: "0;0;-12"
  # Конец.
  end: "0;0;-102"
items:
  # Чтобы добавить имя или описание предмету, укажите name и lore по примеру exit.
  1slot:
    slot: 0
    type: DIAMOND_SWORD
  2slot:
    slot: 1
    type: GOLD_SWORD
# Стенды.
stands:
  # Укажите радиус для появления стендов.
  radiusStands: 5
  # Поставьте таймер до взрыва бомбы.
  timer: 20 # В тиках. 20 тиков - 1 секунда.
  # Укажите где будут появляться стенды.
  # Порядок: тип;X;Y;Z (от места установки схематики)
  locs:
  - "gold_block;-2;1;-24"
  - "bomb_blue;0;1;-36"
  - "diamond_block;2;2;-47"
  - "gold_block;-2;2;-57"
  - "diamond_block;2;1;-69"
  - "bomb_blue;0;1;-79"
  - "bomb_gold;0;0;-94"
# Система оценивания звёзд.
stars:
  # 1 - 100% выполнения.
  # 0.8 - 80% выполнения.
  # 0.1 - 10% выполнения.
  5: 0.9
  4: 0.75
  3: 0.5
  2: 0.3
  1: 0.15
