name: JParkour
version: '1.6'
main: ru.mitriyf.jparkour.JParkour
depend: [ FastAsyncWorldEdit ]
softdepend: [ PlaceholderAPI ]
api-version: 1.13
website: https://github.com/mitriyf/JParkour
authors: [ JDevs, Mitriyf ]
commands:
  jparkour:
    description: game settings