package ru.mitriyf.jparkour.utils.actions;

public enum ActionType {
    ROOM, PARTY, PLAYER, TELEPORT, MESSAGE, ACTIONBAR, CONNECT, TITLE, SOUND, EXPLOSION, EFFECT, CONSOLE, BROADCAST, BOSSBAR, LOG, DELAY
}